# Qdrant配置
QDRANT_URL =
QDRANT_COLLECTION_NAME =  # 第二层：文档内容集合
QDRANT_SUMMARY_COLLECTION_NAME =   # 第一层：文档摘要集合
SQL_Xxk_yibang_COLLECTION_NAME =   # Text2SQL知识库集合
MYSQL_HOST_URL =
MYSQL_USER =
MYSQL_PASSWORD =
MYSQL_DATABASE =

# 文档处理配置
DOCUMENT_PATH_DIR =

Delimiter_based_chunking_size = 200
Delimiter_based_chunk_overlap = 40

CHUNK_SIZE = 1000
CHUNK_OVERLAP = 200

# 嵌入模型配置
#EMBEDDING_MODEL = "Qwen3-Embedding-0.6B"
LLM_MODEL =
XUNFEI_API_BASE =
XUNFEI_API_KEY =
# LLM配置
EMBEDDING_LLM_MODEL =
EMBEDDING_XUNFEI_API_BASE =
# 讯飞星辰大模型配置
EMBEDDING_XUNFEI_API_KEY =
